### PR TITLE
Use fixed thread pools instead of unbounded thread pool executors

### LINKED ISSUE #21: Max num of threads in params is ignored
There are two parameters to configure the number of threads of the thread pools that we use: `prio-threads` (for the priority auth renewer) and `threads` (for the main thread pool). Both of them accept a min and a max. However, the max is ignored.

The reason is that we are using concurrent-ruby's `ThreadPoolExecutor` without specifying a max size for the queue, and that type of pool only spawns a new thread when the queue is full. For more details check: http://ruby-concurrency.github.io/concurrent-ruby/file.thread_pools.html

Specifying a max size for the queue creates new problems, like deciding what to do with new jobs when the queue is full and no new threads can be created. I think that for our use case, a `FixedThreadPool` is fine.

The workaround until we solve this is to specify max:max in the params instead of min:max.

### PR DESCRIPTION
**Pull request by davidor**
Closes #21

### CODE REVIEW

File: exe/xcflushd [hunk 1]
```diff
@@ -31,11 +31,11 @@ command :run do |c|
   c.desc 'Reporting frequency (in seconds)'
   c.flag [:f, :frequency], required: true, type: Integer, must_match: POSITIVE_N_RE
 
-  c.desc 'Number of threads for the main thread pool (min:max)'
-  c.flag [:t, :threads], default_value: 'auto', type: PositiveMinMaxInt
+  c.desc 'Number of threads for the main thread pool'
+  c.flag [:t, :threads], default_value: 'auto', type: Integer, must_match: POSITIVE_N_RE
```
Comment (unleashed) [inline exe/xcflushd]: We cannot break the CLI compatibility. Just add text explaining min is not used.

Comment (davidor) [inline exe/xcflushd]: You're right. I've changed this.

File: lib/xcflushd/threading.rb [hunk 2]
```diff
@@ -3,10 +3,8 @@
 
 module Xcflushd
   module Threading
-    def self.default_threads_value
-      cpus = Concurrent.processor_count
-      # default thread pool minimum is zero
-      return 0, cpus * 4
+    def self.default_threads
+      Concurrent.processor_count
```
Comment (unleashed) [inline lib/xcflushd/threading.rb]: This has been changed to have an effective value of `processor_count` threads instead of 4 times that value. Why? Maybe a bit of testing is needed to see that it really makes no difference, but I'd lean on defaulting to 4 times, since the process is I/O bound and threads are likely to block.

Comment (davidor) [inline lib/xcflushd/threading.rb]: I didn't mean to change the default values. I just didn't notice that `* 4` 🤦‍♂️

Comment (davidor) [inline lib/xcflushd/threading.rb]: Fixed.
